import discord
from redbot.core import commands, Config
from random import randint

BaseCog = getattr(commands, "Cog", object)


class Truth(BaseCog):
    """Conversation games"""

    def __init__(self):
        self.config = Config.get_conf(self, identifier=7631553)
        default_global = {
        "truths": [
                "What is your spirit animal?",
                "Are you an extrovert or introvert?",
                "Are you a cat person or a dog person?",
                "What’s your all time favorite movie?",
                "What is your ultimate dream job?",
                "What was your major in college?",
                "What would you do if you had all the money in the world?",
                "Which do you prefer: city or suburbs?",
                "What did you want to be when you grew up as a child?",
                "What emoji best captures your essence?",
                "What is the most addicting site on the internet?",
                "Do you play any sports?",
                "What was your favorite age?",
                "If you could only eat one food for the rest of your life what would it be?",
                "What’s your zodiac sign?",
                "What is one thing you never get bored of?",
                "Are your a morning or night person?",
                "Do you believe in the paranormal?",
                "What is the first concert you ever attended?",
                "Do you enjoy small talk with strangers, or do you try to avoid it at all costs?",
                "What is one show you never, ever miss an episode of?",
                "What’s the last show you binge-watched?",
                "Who is your favorite band?",
                "What was the last concert you went to?",
                "What was your favorite subject in school?",
                "Do you like to exercise?",
                "Do you like to eat healthily?",
                "Have you ever tried a fad diet craze?",
                "What is your favorite holiday?",
                "What is your favorite time of year?",
                "What are your hobbies?",
                "What is a random food you hate?",
                "Can you speak any other languages?",
                "What’s your favorite dessert?",
                "What is your drink of choice?",
                "Do you like trying new things?",
                "Which famous person would you like to be best friends with?",
                "What is one place you’re dying to travel to?",
                "What is something you’re embarrassingly bad at?",
                "Who are your favorite sports teams?",
                "What is something you’re impressively good at?",
                "Are you an indoor or outdoor person?",
                "Are you spontaneous or a planner?",
                "Where would you want to live if you could live anywhere in the world?",
                "Which female celebrity is your ultimate dream girl?",
                "Which fictional movie character would you want to marry?",
                "Which fictional movie protagonist do you wish you could be more like?",
                "What is the greatest TV show of all time?",
                "What is the greatest movie of all time?",
                "Who is the greatest band of all time?",
                "What is your biggest pet peeve?",
                "Do you play any video games?",
                "Do you play any instruments?",
                "What is the last book you read that you absolutely couldn’t put down?",
                "Are you usually 15 minutes late, or 15 minutes early?",
                "Did you have any pets growing up?",
                "What is your absolute favorite song that you never get sick of?",
                "What is your favorite quote or expression?",
                "What is your favorite line from a song?",
                "What is one thing you can’t live without?",
                "Is your job fulfilling?",
                "What is your favorite movie genre?",
                "What is a popular movie that everyone loved that you hated?",
                "What is your favorite way to start the day?",
                "What is your least favorite food?",
                "If you could live in any historical decade, what would it be?",
                "What’s your favorite board game?",
                "What is your favorite city?",
                "What is your most impressive skill?",
                "What is your hidden talent?",
                "What’s the most exciting thing in your life right now?",
                "What are you completely bored with in life?",
                "Do you cook?",
                "If you could have a superpower what would it be?",
                "What’s something you can’t do?",
                "If you could teach one subject in school, what would it be?",
                "Who is your favorite superhero?",
                "Who is a historical figure you would like to have a drink with?",
                "What’s your favorite app?",
                "What was your first job?",
                "What is your favorite childhood memory?",
                "What is the nicest compliment you’ve ever received?",
                "What is one thing you worried and stressed about that ended up being no big deal?",
                "What skill do you wish you could master?",
                "What’s your Myers Briggs?",
                "What’s your Enneagram?",
                "What’s the most adventurous thing you’ve ever done?",
                "What is one thing no one realizes about you?",
                "If you could bring one musician back from the dead, who would it be?",
                "When is the last time you used YOLO as an excuse to do something?",
                "How do you deal with people you really don’t like?",
                "What is the most expensive thing you’ve ever purchased?",
                "Have you ever had a near-death situation?",
                "What do you do when you’re in the mood to do nothing?",
                "What makes you laugh no matter what?",
                "What is your most prized possession?",
                "What would your perfect day look like?",
                "Did you have a happy childhood?",
                "Do you get along with your parents?",
                "Do you get along with your siblings?",
                "Are you ever judgmental?",
                "Where do you see yourself in ten years?",
                "Where your parents strict?",
                "Have you ever cheated on a test?",
                "How would your family describe you?",
                "What do your friends love most about you?",
                "What is the last thing that really moved you?",
                "Have you ever been caught in a lie?",
                "What do you do when you’re feeling stressed?",
                "Have you ever made a huge drunken mistake?",
                "So you like social media, or think it’s ruining society?",
                "Have you ever had surgery?",
                "What is a risk worth taking?",
                "Is there anyone you admire?",
                "What is the best advice you’ve ever received?",
                "Do you believe in a higher power?",
                "What is a cause you truly believe in?",
                "Do you want to have kids someday?",
                "Do you believe in marriage or think it’s obsolete?",
                "Is it better to be nice or important?",
                "What is your biggest guilty pleasure?",
                "How have you changed since your teenage years?",
                "Is there a mistake you seem to make over and over again?",
                "What do people usually come to you for when they need advice?",
                "Do you have any strange phobias?",
                "What is the best gift you’ve ever received?",
                "Have you ever been in a physical fight?",
                "Does getting older scare you?",
                "What’s one thing you still have from your childhood?",
                "What’s one habit you wish you could break?",
                "What is something you consider absolutely unforgivable?",
                "What did you love most about your hometown?",
                "Do you believe in reincarnation?",
                "What is something that makes you feel like a kid again?",
                "How do you deal with stressful situations?",
                "Are you good at debates?",
                "What advice would you give your teenage self?",
                "What is something you always procrastinate on?",
                "What is the most spontaneous thing you’ve ever done?",
                "What is the title of the story of your life?",
                "What is the toughest lesson you’ve ever learned?",
                "Are you a spender or a saver?",
                "If you could get rid of one technological item, what would it be?",
                "What annoys you most about people?",
                "What qualities do you value in your friends?",
                "What do you have no patience for?",
                "What is your favorite family memory?",
                "What is the best thing that happened to you this year?",
                "What is the bravest thing you’ve ever done?",
                "What is one goal you hope to achieve in your lifetime?",
                "What’s your worst habit?",
                "Were you ever bullied?",
                "Have you ever been a bully?",
                "What was your biggest childhood fear?",
                "What are people always surprised to discover about you?",
                "What is one thing you wish you knew as a child?",
                "Have you ever had your heart broken?",
                "Have you ever broken someone’s heart?",
                "What was the worst part of your childhood?",
                "What surprises you the most about people?",
                "What is your biggest regret in life?",
                "What is the one way you sabotage yourself?",
                "What is the worst decision you’ve ever made?",
                "Have you ever burned any bridges that you regret?",
                "Do you have any recurring dreams?",
                "When is the last time you felt truly, deeply happy?",
                "Would you change anything about your family?",
                "What is one thing you wish you could go back and do again?",
                "Have you ever been in love?",
                "Are you a confident person?",
                "What keeps you up at night?",
                "What are your biggest insecurities?",
                "What are your greatest fears?",
                "What gives your life meaning?",
                "Would you say you truly love yourself?",
                "What is one shameful thing you’ve done that you’ve never told anyone?",
                "Have you ever been cheated on?",
                "What is the most important life lesson for someone to learn?",
                "Have you ever cheated on someone?",
                "When was the last time you had a good cry?",
                "Have you ever been addicted to something?",
                "Has anyone close to you passed away?",
                "What is your biggest weakness?",
                "What do you wish you could be better at?",
                "If you could go back and re-do the last five years, what would you do differently?",
                "What always angers you?",
                "What are your thoughts on the “hookup culture”?",
                "Have you ever experienced a trauma?",
                "Have you ever been on medicine for a mental issue?",
                "Have you ever seen a therapist?",
                "Do your parents have a happy marriage?",
                "Who do you consider to be “relationship goals”?",
                "Have you ever hit rock bottom in life?",
                "Have you ever been in serious trouble?",
                "What makes you feel truly alive?",
                "What was a defining moment in your life?",
                "Do you believe in an afterlife?",
                "What is something you did once and will never do again?",
                "What is something you have strong opinions about?",
                "Do you believe in soul mates?",
                "What is the absolute worst quality a person can have?",
                "What do you like to do for fun?",
                "What would be your perfect date?",
                "What is the most romantic movie you’ve ever seen?",
                "What behavior instantly turns you off?",
                "Do you want a wife who works or one who will be home with the kids?",
                "What physical feature do you always notice first?",
                "What should a healthy relationship provide for the people in it?",
                "How would you describe me in three words?",
                "Do you believe love conquers all?",
                "Alls fair in love and war?",
                "What would be your dream date?",
                "What would be your dream romantic getaway?",
                "Can you tell me a secret you’ve never told anyone else?",
                "Are you a relationship person or do you like to date around?",
                "Do you prefer to go out or stay in?",
                "What is the first thing you notice about a woman?",
                "Where do you see yourself in the next five years?",
                "How would you define love?",
                "What are you most grateful for in life?",
                "What’s more important, love or money?",
                "What was your first impression of me?",
                "What does family mean to you?",
                "What does “manliness” mean to you?",
                "What motivates you in life?",
                "In what way are we totally similar?",
                "In what way are we totally different?",
                "Do you think opposites attract?",
                "What is one thing that always melts your heart?"
          ],      
        "personaltruths": [
                "How old were you when you got your first kiss?",
                "When did you realize you liked me this much?",
                "Do you want to spice up our sex life?",
                "Do you like being kissed in public?",
                "What is your favorite part of a man?",
                "What was your most recent exotic dream, and was I in it?",
                "How often do you think about me when you pleasure yourself",
                "What are your thoughts on sex in public places?",
                "What is the sexiest outfit you own, and would you wear it tonight for me?",
                "Have you ever had a one-night-stand, and how do you feel about them?",
                "When was the first time you realized you wanted to have sex with me?",
                "What are the hottest places you’ve done it, outside of your home?",
                "Which part of your body do you like me to kiss the most?",
                "What are your suggestions to spice up our sex life?",
                "Name all the things you keep in your nightstand.",
                "How many guys have you had sex with, and how do they compare to me?",
                "What is the thing that makes you feel good the most during sex?",
                "Do you like foreplay or do you like going straight to business?",
                "Have you ever tried being blindfolded?",
                "What do you think about handcuffs?",
                "Have you ever used props in the bedroom, and do you want to try it?",
                "Do you like having sex knowing that another couple is watching?",
                "What turns you on the most?",
                "Do you picture me when you masturbate?",
                "Do you bite?",
                "Are you into scratching?",
                "Do you like it when I pull your hair during sex?",
                "Do you want us to have a code word?",
                "Do you like it rough?",
                "How long can you go without sex?",
                "What outfit do you like to see me in the most?",
                "Do you like it when I come inside you?",
                "What is your favorite position, and do you want us to try it tonight?",
                "Do you like flirting through text messages?",
                "What is the naughtiest text you ever sent, and how was it received?",
                "What is your sexiest guilty pleasure?",
                "Have you ever watched another couple have sex?",
                "Does talking dirty turn you on, and do you want to try it with me?",
                "Do you enjoy being asked these naughty questions?",
                "If I was with you right now, what would you like me to do to you?",
                ". Do you enjoy being on top?",
                "Do you like playing sexy games?",
                "Have you ever role-played?",
                "re you into phone sex, and do you want to try it?",
                "What is the most vulgar thing you ever said during sex?",
                "What is your favorite part of your body?",
                "If you could have sex anywhere in the world, where would it be?",
                "Have you ever flirted online with someone you barely kn",
                "How do you feel about sex on the first date?",
                "Where do you enjoy being touched the most?",
                ". Have you ever tried bondage?",
                "What is your favorite position, and do you want us to try it tonight?",
                "Do you like flirting through text messages?",
                "What is the naughtiest text you ever sent, and how was it received?",
                "What is your sexiest guilty pleasure?",
                "Have you ever watched another couple have sex?",
                "Does talking dirty turn you on, and do you want to try it with me?",
                "Do you enjoy being asked these naughty questions?",
                "If I was with you right now, what would you like me to do to you?",
                ". Do you enjoy being on top?",
                "Do you like playing sexy games?",
                "Have you ever role-played?",
                "re you into phone sex, and do you want to try it?",
                "What is the most vulgar thing you ever said during sex?",
                "What is your favorite part of your body?",
                "If you could have sex anywhere in the world, where would it be?",
                "Have you ever flirted online with someone you barely kn",
                "How do you feel about sex on the first date?",
                "Where do you enjoy being touched the most?",
                ". Have you ever tried bondage?",
                "Would you like me to watch you as you pleasure yourself and then join you later?",
                ". Do you like it when I go down on you?",
                "Do you like giving me head?",
                "How can I make it more enjoyable for you?",
                "Are you a screamer?",
                "What is the kinkiest fantasy you have about me, and do you want to make it come to life?",
                "Do you like it when I touch you slowly all over your body?",
                "If you had to choose one position for the rest of your life, which one would you choose?",
                "What is your bedroom bucket list?",
                "What is your favorite part of the day to have sex?",
                "When you get horny in public, how do you deal with that?",
                ". Have you ever had freaky thoughts about your boss?",
                "Do you want to watch porn together?",
                "Have you ever watched another couple have sex without them knowing? Did it turn you on?",
                "Do you like it when I tell you what to do?",
                "Do you have a line you never cross when in bed?",
                "What is a sure way to turn you on within seconds?",
                "What is the most orgasmic thing I could do to you?",
                "What is the kinkiest thing you’ve ever done to your partner?",
                "What’s your favorite pair or underwear?",
                "Where is your favorite spot to be kissed?",
                "How do you feel about kissing in public?",
                "Food before fun or fun before food?",
                "What is one thing that gives you butterflies?",
                "What’s your favorite pair or underwear?",
                "Where is your favorite spot to be kissed?",
                "How do you feel about kissing in public?",
                "Food before fun or fun before food?",
                "What is one thing that gives you butterflies?",
                "Would you rather possess good looks or intelligence?",
                "Do you think about me when I’m away?",
                "What’s the most exotic dream you’ve had about me?",
                "Using three words, how do you feel about me?",
                "If you were to give me a pet name, what would it be?",
                "What are you doing later?",
                "When did you first realize you liked me?",
                "Can you tell me some reasons why I like you?",
                "What do you expect most out of a relationship?",
                "Who should make the first move in a relationship?",
                "Would you like to go on a date with me?",
                "Do you see me in your future?",
                "What is your guilty pleasure?",
                "What is your favorite thing about me?",
                "If I could take you on a date anywhere, where would you want to go?",
                "Do you invite someone in on the first date?",
                "In an ideal world, how long would foreplay be?",
                "Is there a sexy scene from a movie that you want to recreate with me?",
                "If you could only touch me in one place, where would it be?",
                "What's one thing you want me to do to you that I haven't done?",
                "What's the farthest you've gone on a first date?",
                "Have you ever been caught going solo? By who?",
                "Is laughing in the bedroom okay with you or do you prefer keeping things serious?",
                "What's the longest you've gone without doing it?",
                "What's the most number of times you've done it in a row?",
                "Do you like watching me touch myself?",
                "I heard kissing burns a lot of calories. Want to help me exercise?",
                "What do you look for in a partner for the bedroom?",
                "Spit or swallow?",
                "Shave, Trim or Natural?",
                "What do you think about toys in the bedroom?",
                "Does the thought of recording a video turn you on?",
                "What's a naughty fantasy you have about me?",
                "What's one public place where you would want to do it?",
                "What's the best thing a woman can do to you in bed?",
                "Do you prefer to give or receive?",
                "Rough or sensual?",
                "What's the longest intimate session for you?",
                "What was your first time like?",
                "Do you like sexting?",
                "Have you ever done it in front of other people?",
                "Have you ever done it with more than one person in one day?",
                "Have you ever had a friend with benefits?",
                "Have you ever hooked up with someone you weren't supposed to hook up with?",
                "Have you ever used food during intimacy?",
                "Are you part of the mile high club?",
                "Have you ever played strip poker?",
                "Do you like BDSM?",
                "Would you let me pleasure you while you were driving?",
                "What's the dirtiest thing you've though about doing to me?",
                "Where's the most uncomfortable place you've ever done it?",
                "Have you ever fantasized about someone else while making love?",
                "Have you ever done it in the water?",
                "Who do you think of when you pleasure yourself?",
                "What is your biggest turn on?",
                "What is your biggest turn off?",
                "Do you own any toys?",
                "What's the weirdest place you've ever done it?",
                "If you were looking at movies online, what do you look for?",
                "Do you like your hair pulled?",
                "Do you like making out?",
                "What kind of music do you like to play in the bedroom, if any?",
                "Do you like experimenting with different positions?",
                "If your love-making can be described by a weather event or a natural disaster, what would it be?",
                "What do you do when you’re watching a movie with your parents and a certain type of scene comes on?",
                "Would you consider yourself romantic?",
                "How many exes' numbers are still in your phone?",
                "How many single girls/guys' numbers are in your phone?",
                "How many girlfriends or boyfiriends have you had?",
                "Do you like it with the lights on or off?",
                "When you wake up in the morning, what is the first thought that comes to mind when you look at me?",
                 "What is your favourite type of porn?",
                "What is the hottest thing you have ever experienced while having sex?",
                "What’s your secret talent in bed?",
                "What is your favourite sexual position",
                "What sexual act arouses you the most?",
                "What is your favourite type of foreplay?",
                "Describe your ultimate sexual fantasy.",
                "What is the weirdest sexual request you have ever received?",
                "Name 2 sexual things you’re not into.",
                "Tell an erotic story about yourself or one of your friends.",
                "What is the best time of day to have sex?",
                "Tell the group about your last one-night stand.",
                "“It turns me on when somebody calls me …..” during sex.",
                "Tell the group about the longest sex session you have had (with whom and when).",
                "You’re the flirt expert. Give 3 good tips.",
                "What is the extremest sexual act you have ever performed?",
                "What sex act would you never do again?",
                " Who is the most inappropriate person you’ve had a sexual fantasy about?",
                " What’s a sex act most people like that you think is overrated?",
                " If you had to choose between only oral sex or only penetrative sex for the rest of your life, which one would you pick?",
                " Is sex better when you’re in love, or better when the other person is hot and mysterious?",
                " Do you know the last name of everyone you’ve had sex with?",
                " How many sex partners do you believe is “too many”?",
                " What’s #1 on your sexual bucket list right now?",
                " Have you ever taken someone’s virginity?",
                "What do you think is the sexiest body part of your same sex?",
                "What’s something most people don’t like in bed, but you can’t get enough of?",
                " What’s the sexiest thing anyone’s ever said to you?",
                "What’s the least sexy thing anyone’s ever said to you (while trying to be sexy)?",
                "If you had the power to give or receive unlimited orgasms, what would you pick?",
                " What kind of porn did you last watch?",
                "If you could have one sexual superpower, what would it be?",
                "What is a somewhat weird fetish that you would actually try?",
                "What’s the weirdest thing you’ve ever done while masturbating?",
                "If you had to choose between having sex with one person for the rest of your life or never being able to have sex with the same person more than once, what would you pick?",
                "Would you rather pay someone to put on a striptease for you (they aren’t allowed to touch), pay someone to cuddle and massage you while wearing non-sexy clothes, or pay someone to talk dirty over the phone but never be able to see them?",
                "What’s the least sexual thing I’ve done that has gotten you aroused?",
                "What do you wish someone would have told you about sex way earlier?",
                "Has anyone ever caught you having sex?",
                "What non-sexual part of your body turns you on the most when I touch it?",
                "What’s the biggest lie you’ve told in order to get someone into bed?",
                "Have you ever kicked someone out of your bed immediately after having sex?",
                "What one sexual experience would you want to erase from your memory?",
                "What one sexual experience do you think about most often?",
                "Have you ever called someone (or been called) ‘Daddy’?",
                "How much money would your boss have to offer you before you slept with him or her?",
                "Do you have any sex tapes?",
                "What’s your biggest sexual fear?",
                "What is the longest you’ve ever given head?",
                "Have you ever taken it in the butt or would you?",
                "Do you enjoy rough or slow sex?",
                "Do you like anal?",
                "What is your least favourite position?",
                "ell me a fantasy that you have never shared with someone before.",
                "When is the last time you masturbated?",
                "Have you ever swallowed your partners ejaculate?",
                "What’s the sexiest item of clothing you own?",
                "If you could only choose 2 things for me to wear, what would they be?",
                "Have you ever refused to go down on a girl/guy? Why?",
                "Is there someone who everyone thinks is hot, but you think is ugly?",
                "What is the weirdest thing that turns you on?"
          ],
     "newquestions": [
                "What’s the scariest thing you’ve ever done?",
                "What’s your biggest regret?",
                "What’s the most childish thing you’ve ever done?",
                "What’s a bad habit you have?",
                "What’s one thing on your bucket list?",
                "What’s one thing you would do if you waked up tomorrow as the opposite sex?",
                "What’s the last dream you had? Describe.",
                "Have you ever shared a toothbrush with anyone?",
                "Have you ever told a lie and got caught?",
                "What’s one thing you like, and one thing you dislike about yourself?",
                "Have you ever done something embarrassing while drunk? Describe.",
                "If you could change one thing about your life, what would it be?",
                "What are you afraid of?",
                "Have you ever sent an inappropriate/embarrassing text to someone? Describe.",
                "Have you ever stalked someone on Facebook?",
                "Who are you most jealous of and why?",
                "What color is your underwear?",
                "What do you hate and why?",
                "Who/what is someone/something that annoys you?",
                "If you could go anywhere in the world, where would you go?",
                "Have you ever been in love?",
                "What’s something in your web browsing history that you’d be embarrassed if someone saw?",
                "What would you do with your time if you didn’t have to work?",
                "What’s the worst thing that’s ever happened to you?",
                "What’s one thing you can’t live without?",
                " When’s the last time you took a shower?",
                " Have you ever lied or done something to get out of trouble?",
                " What’s the best purchase you ever made?",
                " What’s the most illegal thing you’ve ever done.",
                "Have you ever been arrested",
                "What would you do with a million dollars?",
                "What do you believe in?",
                "Have you ever shared a secret you shouldn’t have, or promised you wouldn’t?",
                "What’s something you’re looking forward to and not looking forward to?",
                "What’s something you think is absolutely disgusting?",
                " When was the last time you cried and why?",
                " If you could live anywhere, where would it be?",
                "What’s your biggest pet peeve?",
                "What do you value most in your relationships?",
                "If you could have three wishes, what would you wish for? What is your secret vice/guilty pleasure?",
                "What’s the most embarrassing thing you’ve ever done?",
                "What’s the worst gift you’ve ever received?",
                "What’s the last thing you searched on your phone?",
                "Have you ever been so drunk you blacked out?",
                "What’s the most embarrassing thing your parents have caught you doing?",
                "What’s the biggest romantic fail you’ve ever experienced?",
                " What’s the biggest secret you’ve ever kept from your boyfriend or girlfriend?",
                "What’s the biggest lie you’ve ever told your boyfriend or girlfriend—without getting caught?",
                "What do you like most and least about your own appearance?",
                "What do you like most and least about your significant other’s appearance?",
                "What’s the craziest thing you’ve ever done to attract a crush?",
                "If you could make out with any celebrity right this second, who would it be?",
                "At what age did you first start having sexy thoughts and what prompted them?",
                "What’s the cruelest thing you’ve ever done to a boyfriend or girlfriend?",
                "What’s your favorite sex toy (hypothetically, or from experience)?",
                "What’s the biggest sexual regret you have?",
                "What’s the biggest dating disappointment you’ve experienced so far?",
                "Do you ever catch yourself thinking about doing it with someone of the same sex?",
                " Have you ever been a thief and stolen something?",
                "What’s the most deviant thing you have ever done?",
                "What’s your craziest sexual fantasy?",
                " Have you ever been extremely rude to someone you know?",
                "Do you have anything hidden in your house that no one knows about?",
                "Have you ever had sex with someone who you didn’t like?",
                "What’s something that only you know about yourself that no one would guess",
                "Have you ever been arrested? Have you ever had to get “physical” with someone during an altercation?",
                "If you had to cheat who would it be with?",
                "What’s your worst nightmare?",
                "What would cause you to break up with you girlfriend/boyfriend?",
                "What’s the most ridiculous reason that you have ever broken up with someone over?",
                "What is the grossest habit that you have?",
                "What do you think is your best feature? And what is the worst?",
                "What’s the bravest thing you’ve ever done?",
                "Who in the round would you like to turn into a pig?",
                "When was the last time you peed the bed?",
                "If you were going to make your money illegally, how would you make it?",
                "What is something childish that you still do?",
                "If you were blind, who in the round would be your guide dog?",
                "What can impress you the most?",
                "If you were allowed to use only 3 words for the rest of the evening from now on - which would it be?",
                "If you were a dictator, which law would you legislate first?",
                "If you had lived during the Nazi era, who would you have been?",
                "What was the most embarrassing experience in your school time?",
                "What was the biggest mistake of your life?",
                "What would you never do - even if you know you only have 12 more hours to live?",
                "What offense have you committed?",
                "Tell me a secret from your childhood.",
                "What’s your biggest (secret) vice?",
                "What would you like to do with me … (or person xy), if you could then erase my (her, his …) memory?",
                "What’s the worst thing you’ve ever done to anyone?",
                "Whom have you had the biggest crush on?",
                "Have you ever been in love with one of those present?",
                "If you were a vampire, who of us would you bite now?",
                "What’s the worst thing you’ve ever experienced?",
                "What was your worst time you have been rejected?",
                "Have you ever pooped your pants in public?",
                "What is your darkest fantasy?",
                "What’s the nicest thing you’ve ever experienced with another person?",
                "What is the greatest turn-off for you?",
                "What party do you like most about your body and what’s the ugliest?",
                "Who from our round would you like to see naked?",
                "Who in the round could you fall in love with most?",
                "Have you ever had an erotic dream in which someone from this round occurred?",
                "If you would tattoo yourself in the genital area - what would be there?",
                "What’s more important in a relationship - sex or love?",
                "Do you think sex is cool, good, okay, sometimes nice - or is not it so important to you?",
                "What makes sex really good?",
                "How many times a week/month do you have sex - and how often would you like to have sex?",
                "How many different sex partners have you already slept with?",
                "Which part of the body turns you on the most?",
                "How, where and with whom did you have your first time?",
                "How important is extended foreplay for you?",
                "What does a man/woman have to do to seduce you?",
                "Have you ever had a threesome? And how did you like it?",
                "Have you ever had sex with a good friend?",
                "Did you ever have sex with one of this group - except your partner?",
                "How do you prepare for a date?",
                "You move to a lonely island, who from the group do you take with you?",
                "What are you most afraid of?",
                "Where do you shave everywhere?",
                "Do you have a nickname?",
                "Are you looking into the toilet bowl before you flush?",
                "Who gave you the worst heartache?",
                "How many times have you kissed?",
                "What’s the most embarrassing thing that ever happened to you?",
                "How many guys/girls have you already kissed?",
                "Who are you in love with?",
                "Which star do you like hot?",
                "Would you make out with XY (insert name)?",
                "Have you ever stolen something?",
                "Do you still have a stuffed animal in your bed?",
                "What was the most awkward phone call you’ve ever had?",
                "Have you ever been in love with your best friend?",
                "Do you moan at orgasm?",
                "Have you ever been caught masturbating?",
                "Did you ever stuff your bra?",
                "When was the last time you had sex?",
                "hen and where did you last have sex?",
                "What is your favourite type of porn?",
                "What is the hottest thing you have ever experienced while having sex?",
                "What’s your secret talent in bed?",
                "What does it take for you to have an one-night stand?",
                "What sexual act arouses you the most?",
                "What is your favourite type of foreplay?",
                "Describe your ultimate sexual fantasy.",
                "What is the weirdest sexual request you have ever received?",
                "How many sexual partners have you had the past year?",
                "Name 2 sexual things you’re not into.",
                "Tell an erotic story about yourself or one of your friends.",
                "What is the best time of day to have sex?",
                "What are your main usernames for internet sites?",
                "Tell the group about your last one-night stand.",
                "What is your guilty pleasure?",
                "“It turns me on when somebody calls me …..” during sex.",
                "You’re the flirt expert. Give 3 good tips.",
                "What is the extremest sexual act you have ever performed?",
                "What’s your favorite go-to move for getting attention from the opposite sex?",
                "What would you change about your life if you could?",
                "What’s the most flirtatious thing you’ve ever done?",
                "If you could make one wish right this second, what would it be?",
                "What three adjectives best describe your vagina/penis?",
                "What does the perfect male/female body look like (from head to toe and everything in between) in your opinion?",
                "How many people can someone sleep with before you secretly judge them for their “number”?",
                "What’s the one thing you’d do in bed with someone if you had no inhibitions whatsoever?",
                "What’s sexual milestone has been most memorable for you so far?",
                "What’s the weirdest thing you’ve ever done in front of the mirror?",
                "What sex act have you've done that you'll never do again?",
                "Do you love me? How much?",
                "Where do you see this going?",
                "How many partners have you had?",
                "How many people have you kissed?",
                "When was a time you were so turned on you couldn't stand it?",
                "Hmany times a week do you touch yourself?",
                "Have you ever done it at work?",
                "What’s something that you always wanted to say to me but couldn’t? ",
                "How would you sound if you picked up a random book and read it in the most seductive voice you can?  ",
                "Have you ever flashed someone?  ",
                "Have you ever shared a toothbrush with someone? ",
                "What’s the color of your underwear? ",
                "Who was the last person you checked out?  ",
                "Which movie star do you think is the hottest? ",
                "How would you rate my looks on a scale of 1 to 10? ",
                "Do you sleep without your clothes? ",
                "If you could marry more than one person, how many people would you marry, and who would they be? ",
                "Who is the one person that you have met that had the stinkiest armpits?  ",
                "Who do you hate and why? ",
                "If you were to kiss a person of the same gender, who would it be? ",
                "When was the last time you had a sexual dream? Who was it about? ",
                "How old were you when you lost your virginity? ",
                "Have you ever faked an orgasm during sex?  ",
                "What’s the biggest turn-on to you while making out with someone?   ",
                "Have you ever had the fantasy of making out in the shower?",
            ],

                

        }
        self.config.register_global(**default_global)



    @commands.command()
    @commands.bot_has_permissions(embed_links=True)
    async def yourtruth(self, ctx, *, user: discord.Member):
        """Ask a truth question to users!"""

        # Set author
        author = ctx.message.author

        # Get and pick random string
        strings = await self.config.truths()
        mn = len(strings)
        rs = randint(0, mn - 1)

        # Get and pick random user
        mn2 = len(ctx.guild.members)
        rp = randint(0, mn2 - 1)
        name = ctx.guild.members[rp].mention

        # Build Embed
        embed = discord.Embed()
        embed.title = f"{author.name} asked {user.name}"
        embed.description = strings[rs].format(name=name)
        await ctx.send(embed=embed)

   
        # Build Embed
        embed = discord.Embed()
        embed.title = f"{author.name} dared {user.name}"
        embed.description = strings[rs].format(name=name)
        await ctx.send(embed=embed)

    @commands.command()
    @commands.bot_has_permissions(embed_links=True)
    async def curious(self, ctx, *, user: discord.Member):
        """Ask a truth question to users!"""

        # Set author
        author = ctx.message.author

        # Get and pick random string
        strings = await self.config.newquestions()
        mn = len(strings)
        rs = randint(0, mn - 1)

        # Get and pick random user
        mn2 = len(ctx.guild.members)
        rp = randint(0, mn2 - 1)
        name = ctx.guild.members[rp].mention

        # Build Embed
        embed = discord.Embed()
        embed.title = f"{author.name} is curious {user.name}"
        embed.description = strings[rs].format(name=name)
        await ctx.send(embed=embed)
