import discord
from redbot.core import commands, Config
from random import randint

BaseCog = getattr(commands, "Cog", object)


class Truth(BaseCog):
    """Conversation games"""

    def __init__(self):
        self.config = Config.get_conf(self, identifier=7631553)
        default_global = {
        "truths": [
                "What is your spirit animal?",
                "Are you an extrovert or introvert?",
                "Are you a cat person or a dog person?",
                "What’s your all time favorite movie?",
                "What is your ultimate dream job?",
                "What was your major in college?",
                "What would you do if you had all the money in the world?",
                "Which do you prefer: city or suburbs?",
                "What did you want to be when you grew up as a child?",
                "What emoji best captures your essence?",
                "What is the most addicting site on the internet?",
                "Do you play any sports?",
                "What was your favorite age?",
                "If you could only eat one food for the rest of your life what would it be?",
                "What’s your zodiac sign?",
                "What is one thing you never get bored of?",
                "Are your a morning or night person?",
                "Do you believe in the paranormal?",
                "What is the first concert you ever attended?",
                "Do you enjoy small talk with strangers, or do you try to avoid it at all costs?",
                "What is one show you never, ever miss an episode of?",
                "What’s the last show you binge-watched?",
                "Who is your favorite band?",
                "What was the last concert you went to?",
                "What was your favorite subject in school?",
                "Do you like to exercise?",
                "Do you like to eat healthily?",
                "Have you ever tried a fad diet craze?",
                "What is your favorite holiday?",
                "What is your favorite time of year?",
                "What are your hobbies?",
                "What is a random food you hate?",
                "Can you speak any other languages?",
                "What’s your favorite dessert?",
                "What is your drink of choice?",
                "Do you like trying new things?",
                "Which famous person would you like to be best friends with?",
                "What is one place you’re dying to travel to?",
                "What is something you’re embarrassingly bad at?",
                "Who are your favorite sports teams?",
                "What is something you’re impressively good at?",
                "Are you an indoor or outdoor person?",
                "Are you spontaneous or a planner?",
                "Where would you want to live if you could live anywhere in the world?",
                "Which female celebrity is your ultimate dream girl?",
                "Which fictional movie character would you want to marry?",
                "Which fictional movie protagonist do you wish you could be more like?",
                "What is the greatest TV show of all time?",
                "What is the greatest movie of all time?",
                "Who is the greatest band of all time?",
                "What is your biggest pet peeve?",
                "Do you play any video games?",
                "Do you play any instruments?",
                "What is the last book you read that you absolutely couldn’t put down?",
                "Are you usually 15 minutes late, or 15 minutes early?",
                "Did you have any pets growing up?",
                "What is your absolute favorite song that you never get sick of?",
                "What is your favorite quote or expression?",
                "What is your favorite line from a song?",
                "What is one thing you can’t live without?",
                "Is your job fulfilling?",
                "What is your favorite movie genre?",
                "What is a popular movie that everyone loved that you hated?",
                "What is your favorite way to start the day?",
                "What is your least favorite food?",
                "If you could live in any historical decade, what would it be?",
                "What’s your favorite board game?",
                "What is your favorite city?",
                "What is your most impressive skill?",
                "What is your hidden talent?",
                "What’s the most exciting thing in your life right now?",
                "What are you completely bored with in life?",
                "Do you cook?",
                "If you could have a superpower what would it be?",
                "What’s something you can’t do?",
                "If you could teach one subject in school, what would it be?",
                "Who is your favorite superhero?",
                "Who is a historical figure you would like to have a drink with?",
                "What’s your favorite app?",
                "What was your first job?",
                "What is your favorite childhood memory?",
                "What is the nicest compliment you’ve ever received?",
                "What is one thing you worried and stressed about that ended up being no big deal?",
                "What skill do you wish you could master?",
                "What’s your Myers Briggs?",
                "What’s your Enneagram?",
                "What’s the most adventurous thing you’ve ever done?",
                "What is one thing no one realizes about you?",
                "If you could bring one musician back from the dead, who would it be?",
                "When is the last time you used YOLO as an excuse to do something?",
                "How do you deal with people you really don’t like?",
                "What is the most expensive thing you’ve ever purchased?",
                "Have you ever had a near-death situation?",
                "What do you do when you’re in the mood to do nothing?",
                "What makes you laugh no matter what?",
                "What is your most prized possession?",
                "What would your perfect day look like?",
                "Did you have a happy childhood?",
                "Do you get along with your parents?",
                "Do you get along with your siblings?",
                "Are you ever judgmental?",
                "Where do you see yourself in ten years?",
                "Where your parents strict?",
                "Have you ever cheated on a test?",
                "How would your family describe you?",
                "What do your friends love most about you?",
                "What is the last thing that really moved you?",
                "Have you ever been caught in a lie?",
                "What do you do when you’re feeling stressed?",
                "Have you ever made a huge drunken mistake?",
                "So you like social media, or think it’s ruining society?",
                "Have you ever had surgery?",
                "What is a risk worth taking?",
                "Is there anyone you admire?",
                "What is the best advice you’ve ever received?",
                "Do you believe in a higher power?",
                "What is a cause you truly believe in?",
                "Do you want to have kids someday?",
                "Do you believe in marriage or think it’s obsolete?",
                "Is it better to be nice or important?",
                "What is your biggest guilty pleasure?",
                "How have you changed since your teenage years?",
                "Is there a mistake you seem to make over and over again?",
                "What do people usually come to you for when they need advice?",
                "Do you have any strange phobias?",
                "What is the best gift you’ve ever received?",
                "Have you ever been in a physical fight?",
                "Does getting older scare you?",
                "What’s one thing you still have from your childhood?",
                "What’s one habit you wish you could break?",
                "What is something you consider absolutely unforgivable?",
                "What did you love most about your hometown?",
                "Do you believe in reincarnation?",
                "What is something that makes you feel like a kid again?",
                "How do you deal with stressful situations?",
                "Are you good at debates?",
                "What advice would you give your teenage self?",
                "What is something you always procrastinate on?",
                "What is the most spontaneous thing you’ve ever done?",
                "What is the title of the story of your life?",
                "What is the toughest lesson you’ve ever learned?",
                "Are you a spender or a saver?",
                "If you could get rid of one technological item, what would it be?",
                "What annoys you most about people?",
                "What qualities do you value in your friends?",
                "What do you have no patience for?",
                "What is your favorite family memory?",
                "What is the best thing that happened to you this year?",
                "What is the bravest thing you’ve ever done?",
                "What is one goal you hope to achieve in your lifetime?",
                "What’s your worst habit?",
                "Were you ever bullied?",
                "Have you ever been a bully?",
                "What was your biggest childhood fear?",
                "What are people always surprised to discover about you?",
                "What is one thing you wish you knew as a child?",
                "Have you ever had your heart broken?",
                "Have you ever broken someone’s heart?",
                "What was the worst part of your childhood?",
                "What surprises you the most about people?",
                "What is your biggest regret in life?",
                "What is the one way you sabotage yourself?",
                "What is the worst decision you’ve ever made?",
                "Have you ever burned any bridges that you regret?",
                "Do you have any recurring dreams?",
                "When is the last time you felt truly, deeply happy?",
                "Would you change anything about your family?",
                "What is one thing you wish you could go back and do again?",
                "Have you ever been in love?",
                "Are you a confident person?",
                "What keeps you up at night?",
                "What are your biggest insecurities?",
                "What are your greatest fears?",
                "What gives your life meaning?",
                "Would you say you truly love yourself?",
                "What is one shameful thing you’ve done that you’ve never told anyone?",
                "Have you ever been cheated on?",
                "What is the most important life lesson for someone to learn?",
                "Have you ever cheated on someone?",
                "When was the last time you had a good cry?",
                "Have you ever been addicted to something?",
                "Has anyone close to you passed away?",
                "What is your biggest weakness?",
                "What do you wish you could be better at?",
                "If you could go back and re-do the last five years, what would you do differently?",
                "What always angers you?",
                "What are your thoughts on the “hookup culture”?",
                "Have you ever experienced a trauma?",
                "Have you ever been on medicine for a mental issue?",
                "Have you ever seen a therapist?",
                "Do your parents have a happy marriage?",
                "Who do you consider to be “relationship goals”?",
                "Have you ever hit rock bottom in life?",
                "Have you ever been in serious trouble?",
                "What makes you feel truly alive?",
                "What was a defining moment in your life?",
                "Do you believe in an afterlife?",
                "What is something you did once and will never do again?",
                "What is something you have strong opinions about?",
                "Do you believe in soul mates?",
                "What is the absolute worst quality a person can have?",
                "What do you like to do for fun?",
                "What would be your perfect date?",
                "What is the most romantic movie you’ve ever seen?",
                "What behavior instantly turns you off?",
                "Do you want a wife who works or one who will be home with the kids?",
                "What physical feature do you always notice first?",
                "What should a healthy relationship provide for the people in it?",
                "How would you describe me in three words?",
                "Do you believe love conquers all?",
                "Alls fair in love and war?",
                "What would be your dream date?",
                "What would be your dream romantic getaway?",
                "Can you tell me a secret you’ve never told anyone else?",
                "Are you a relationship person or do you like to date around?",
                "Do you prefer to go out or stay in?",
                "What is the first thing you notice about a woman?",
                "Where do you see yourself in the next five years?",
                "How would you define love?",
                "What are you most grateful for in life?",
                "What’s more important, love or money?",
                "What was your first impression of me?",
                "What does family mean to you?",
                "What does “manliness” mean to you?",
                "What motivates you in life?",
                "In what way are we totally similar?",
                "In what way are we totally different?",
                "Do you think opposites attract?",
                "What is one thing that always melts your heart?"
          ]
        }
        self.config.register_global(**default_global)



    @commands.command()
    @commands.bot_has_permissions(embed_links=True)
    async def yourtruth(self, ctx, *, user: discord.Member):
        """Ask a truth question to users!"""

        # Set author
        author = ctx.message.author

        # Get and pick random string
        strings = await self.config.truths()
        mn = len(strings)
        rs = randint(0, mn - 1)

        # Get and pick random user
        mn2 = len(ctx.guild.members)
        rp = randint(0, mn2 - 1)
        name = ctx.guild.members[rp].mention

        # Build Embed
        embed = discord.Embed()
        embed.title = f"{author.name} asked {user.name}"
        embed.description = strings[rs].format(name=name)
        await ctx.send(embed=embed)

   
        # Build Embed
        embed = discord.Embed()
        embed.title = f"{author.name} dared {user.name}"
        embed.description = strings[rs].format(name=name)
        await ctx.send(embed=embed)